### ISSUE TITLE
Ask to open online version if Assistant not availiable

### ISSUE THREAD

**Issue by ghost** [OpenOrienteering/mapper-manual#18]
Add messagebox with information "Open online Help?" if there no Assistant installed or cant open local help.

**Comment by dg0yt** [comment]
All our PC packages include or recommend Qt Assistant. Why shall we add a dialog for something which is not recommended?

**Comment by ghost** [comment]
As I know, LinuxMint (and Ubuntu) not include "qt5-dev-tools" by default, and if I try install OOMapper DEB using GDebi it not ask me to install "qt5-dev-tools", so user of this OS don't get any warning for that.
I not say make "qt5-dev-tools" hard dependency, no, I mean that Mapper must detect are help browser opened from menu succes and if not give a warning inside Mapper UI.

**Comment by dg0yt** [comment]
This asks for a change in mapper, not mapper-manual.
