### ISSUE TITLE
PDF version

### ISSUE THREAD

**Issue by ghost** [OpenOrienteering/mapper-manual#19]
Add possibility convert this manual to PDF document.

**Comment by dg0yt** [comment]
Go ahead and contribute.

**Comment by ghost** [comment]
> Go ahead and contribute.

As you know, I'm working on it...
![OOMapper Book](https://sourceforge.net/p/oorienteering/tickets/_discuss/thread/59b32cbb/6ee6/attachment/oo%20Mapper%20book.png)
- https://github.com/openOrienteering/mapper/issues/247

But as for me it would be usefull make "mapper-manual" similar to FontForge manual, that has infrastructure ready to autogenerating PDF and other e-book formats.
- https://github.com/fontforge/designwithfontforge.com

**Comment by dg0yt** [comment]
I can't see that infrastructure at fontforge. But we do use doxygen. So there is indeed an option generate PDF directly or via LaTeX.

(Note that all the processing is implemented in the mapper repository. This repository is for editing and online version.)

**Comment by dg0yt** [comment]
Done in https://github.com/OpenOrienteering/mapper/commit/ba2980d. Preview:

[Mapper 0.8.0 Manual Preview.pdf](https://github.com/OpenOrienteering/mapper-manual/files/1512883/Mapper.0.8.0.Manual.Preview.pdf)
