### ISSUE TITLE
</table> showing on View Menu page

### ISSUE THREAD

**Issue by wanacode** [OpenOrienteering/mapper-manual#25]
On the View Menu page their is a stray table tag right below the main title.

http://www.openorienteering.org/mapper-manual/pages/view_menu.html

![screenshot at 2017-07-02 18-43-59](https://user-images.githubusercontent.com/2317149/27767794-840bc322-5f56-11e7-9438-db76decd96b9.png)

The original html code looks okay, so might be something to do with the publishing process. I couldn't work out how to fix it.

**Comment by dg0yt** [comment]
Hm. There might be another error in the HTML markup.

For easier editing (contributing) I would prefer these pages to be converted to Markdown. The toolbars page may serve as an example: https://github.com/OpenOrienteering/mapper-manual/blob/gh-pages/pages/toolbars.md

**Comment by wanacode** [comment]
I see the File Menu page also has a `</table>` tag showing. 

The Edit Menu and Map Menu pages don't have the table tag showing but are using html rather than markdown, along with a few other pages. 

I take it you would prefer all manual pages to be in markdown?

**Comment by dg0yt** [comment]
I suppose markdown makes it easier to contribute than HTML ("Edit this page on Github"), even if the output is more restricted. That's why I would be glad to see all pages converted.
