### ISSUE TITLE
Fix shortcuts in "view_menu.md"

### ISSUE THREAD

**Issue by ghost** [OpenOrienteering/mapper-manual#35]
Need fix shortcuts on "View Menu" page:
* https://github.com/OpenOrienteering/mapper-manual/blob/gh-pages/pages/view_menu.md

* Now they look like: `(Key)`, `Key`
* On all other pages now used style: `**Key**`

**Comment by dg0yt** [comment]
There is a reason for writing `(F6)`, and it is given in the text.
