### ISSUE TITLE
CRT files not working with OCAD file

### ISSUE THREAD

**Issue by dfgeorge** [OpenOrienteering/mapper-manual#38]
Im trying to convert a map that started in OCAD to ISOM 2017 symbols. I have tried Symbols->Replace Symbol Set, then selecting the ISOM 2017 symbol set and loading the ISOM2000-ISOM2017.crt. This does not select all the symbols. I have also tried creating a OCD-ISOM2017.crt, and changing the Symbol Set ID, no luck.

Only thing I could get to work was first replacing the symbol set with with an ISOM2000, matched on number, then replacing that.

file attached with ocad
[test_crt_ocad.zip](https://github.com/OpenOrienteering/mapper-manual/files/1691619/test_crt_ocad.zip)
 symbol set and a few random symbols

**Comment by dg0yt** [comment]
Well, there is no magic here. Our CRT files are designed and tested to work with our symbol sets. It cannot deal with symbol variants which differ in code number or type. But you can adjust the missing pieces, and save the result as a CRT file, in case you need it again.

Note: This ist the mapper-manual repository, for reporting documentation issues.
