### ISSUE TITLE
Autogenerated PDF manuals naming

### ISSUE THREAD

**Issue by ghost** [OpenOrienteering/mapper-manual#40]
Currently there are 3 versions of PDF manual:

- `OpenOrienteering-Mapper-0.x.x-Manual.pdf` - https://download.opensuse.org/repositories/home:/dg0yt/Windows/OpenOrienteering-Mapper-0.8.1-Manual.pdf.zip
- `OpenOrienteering-Mapper-master_0.x.YYYYMMDD-Manual` - https://download.opensuse.org/repositories/home:/dg0yt/Windows/OpenOrienteering-Mapper-master_0.8.20180805-Manual.pdf.zip
- `OpenOrienteering-Mapper-master-qt59_0.x.YYYYMMDD-Manual.pdf` - https://download.opensuse.org/repositories/home:/dg0yt/Windows/OpenOrienteering-Mapper-master-qt59_0.8.20180805-Manual.pdf.zip

For what reason you generate `OpenOrienteering-Mapper-master-qt59_0.x.YYYYMMDD-Manual.pdf`?

**Comment by dg0yt** [comment]
The manual is generated for releases and for master builds. -qt59_ differs only in Qt version from the regular master build, so it builds a manual.

**Comment by ghost** [comment]
> `master-qt59_` differs only in Qt version from the regular master build, so it builds a manual.

But its content is same as `master`, so maybe need exclude generating `master-qt59_`?
