### ISSUE TITLE
O-Map Wiki (collaborative wiki project)

### ISSUE THREAD

**Issue by ghost** [OpenOrienteering/mapper-manual#41]
*Luděk Krtička* («Orienteering Mappers Int.» Facebook group staff) proposed reborn «O-wiki» (discontinued) wiki site as new «O-Map Wiki» for collecting info & docs about all aspects of orienteering mapping & orienteering software, including section about *OpenOrienteering Mapper*:

- https://facebook.com/groups/485564718218028?view=permalink&id=1880528808721605

> This is something I was talking about at ICOM in Prague: O-Map Wiki project. I would like to hear your opinion and suggestions. Also, I would like to invite you to make comments to the structure and content of the project proposal.
> 
> - https://docs.google.com/document/d/1hKtoPnmP7QZpnxPJ6-8WLSm15vUesoxaJuU-Nsi8S-I/

P.S.: I would took part in writing articles for «O-Map Wiki» on some aspects of OpenOrienteering Mapper usage.

### REFERENCE

- http://ol-wiki.de
- http://web.archive.org/web/*/http://o-wiki.net
- http://uk.wikipedia.org/wiki/OpenOrienteering_Mapper

**Comment by ghost** [comment]
Here is «O-Map Wiki project» presentation (PDF) from 18th ICOM:

- https://orienteering.org/wp-content/uploads/2018/10/ICOM2018_Krticka_O-Map-Wiki_project.pdf

P.S.: Here is direct link to PDF-file of full «O-Map Wiki project» documentation

- https://docs.google.com/document/d/1hKtoPnmP7QZpnxPJ6-8WLSm15vUesoxaJuU-Nsi8S-I/export?format=pdf

**Comment by dg0yt** [comment]
Hopefully @krticka finds more contributors than this manual.

**Comment by ghost** [comment]
### IOF Map Commission Meeting, December 7th, 2021

- https://onedrive.live.com/?authkey=%21APu%5FfNV4FAz16Fo&cid=663580750D0C0BCE&id=663580750D0C0BCE%2147162&parId=663580750D0C0BCE%2146502&o=OneUp
  - PDF: [IOF Map Commission Meeting Minutes 2021-4.pdf](https://github.com/OpenOrienteering/mapper/files/7804596/IOF.Map.Commission.Meeting.Minutes.2021-4.pdf)

> #### O-Map Wiki
>
> The project is in progress.
>
> LK will transmit the information to the Map commission members on how to connect. RD will load all the symbols.
