### ISSUE TITLE
Site redirection not working for https://openorienteering.org

### ISSUE THREAD

**Issue by ghost** [OpenOrienteering/mapper-manual#45]
Bad URL:

- `https://openorienteering.org/*`

Good URL:

- `https://www.openorienteering.org/*`

Is it possible to fix redirection from `https://openorienteering.org/*` to `https://www.openorienteering.org/*`?

**Comment by dg0yt** [comment]
No, https://openorienteering.org/ cannot be fixed easily with our current setup. We already looked into this when switching to HTTPS.

However, the lazy may use http://openorienteering.org/
