### ISSUE TITLE
Undocumented restriction on types of geospatial data

### ISSUE THREAD

**Issue by tdobra** [OpenOrienteering/mapper-manual#61]
The page pages/gdal.md suggests that all geospatial raster data can be used as templates. However, Mapper throws an error when trying to open data saved as GrayFloat32, which is a common internal format in GeoTIFFs representing data like height, slope etc. It appears that this data must first be saved in the GeoTIFF as RGB values, presumably a triplet of UInt8s (I'm guessing here). This restriction also occurs with other file extensions. This is an undocumented restriction on types of data that Mapper can load.

I have not encountered any restrictions on vector data. In particular, I can directly load the contour export from QGIS into Mapper.

I suggest updating the GDAL page to explain this (it would have saved me hours today). If it is appropriate to include, the instructions for exporting raster scalars from QGIS are: Calculate and make pretty your layer (e.g. of slope). Go to Layer->Save As. Change the Output mode to Rendered image. Input your file name and any other parameters. Click OK.

Mapper version: 0.9.4

**Comment by dg0yt** [comment]
Well, "all" is always a much too wide term. So far, Mapper does display graphical templates, either raster or vector, It does not yet process raw data into graphics. We can make this more explicit in the documentation. 
But I I don't think we will add QGIS instructions.

**Comment by tdobra** [comment]
I did say "suggests" all types, i.e. I think the documentation can be worded better. Yes, please do make it more explicit, along the lines of your second sentence.

**Comment by dg0yt** [comment]
Would you like to contribute a proposal?

**Comment by tdobra** [comment]
Yes certainly, I'll add in a sentence or two. Prior to your replies, I was still a little unsure about which files are supported.
